### ISSUE TITLE
pane is zero pixels tall

### ISSUE THREAD

**Issue by mark-hahn** [romgrk/termrk#1]
When I toggle termrk using alt-space or ctrl-shift-P, I get a pane with a height of 0 px.  All I see is a tiny gray border.  If I go into the dev tools and set the height manually I can see the black pane.  Alt-space toggles the visibility of the pane.

At that point I can't figure out how to use it.  None of the key combos except alt-space seem to do anything.  Of course it could be my fault for not understanding how it works.

atom 198
ubuntu 14.04
apm  0.166.0
npm  2.5.1
node 0.10.35
python 2.7.6
git 1.9.1

**Comment by romgrk** [comment]
Couldn't reproduce the problem, but I've added a stricter handling/catching of panel height 1ed8aabe483caa9f9294ae3bda85a1607937b124, so it should be ok. Please re-open if the problem persists.
(And thanks for the feedback!)
