### ISSUE TITLE
Run mocha and other such scripts

### ISSUE THREAD

**Issue by jacinto123** [romgrk/termrk#14]
Not sure if this is planned or even in the scope of the project but I would love to be able to run mocha or  nodemon.

**Comment by romgrk** [comment]
I tested mocha, didn't found any problem. Should work for nodemon.
![mocha test](https://raw.githubusercontent.com/romgrk/termrk/master/static/mocha.gif)

**Comment by jacinto123** [comment]
Maybe I am missing something but when I try and do it I get the following error:

![screen shot 2015-05-27 at 10 27 24 pm](https://cloud.githubusercontent.com/assets/1666324/7853188/a90ddb04-04bf-11e5-8117-c6c241b169d5.png)

**Comment by romgrk** [comment]
It appears that `node` isn't found. Is it on your $PATH?

EDIT: Make sure `node` is installed _globally_, not just in your own user path.

**Comment by jacinto123** [comment]
Is there a way I can add to my $PATH in this?

**Comment by romgrk** [comment]
No. That should be done in your `~/.profile`. Something like this.

```
PATH=$PATH:/folder/with/node/bin
```
