### ISSUE TITLE
Alt+space does not toggle the panel

### ISSUE THREAD

**Issue by miguelamello** [romgrk/termrk#17]
In Fedora 21, Termrk alt+space keybind does not toggle the pane.

**Comment by romgrk** [comment]
Does alt-space toggle any other command?

**Comment by miguelamello** [comment]
Hi Rom. I got it!!! Yes it does toggle another command in Gnome Shell. So, it was just the case to change Gnome Shell "Alt+Space" to something different, and this released "Alt+Space" for Termrk.  Thank you, and congratulations for the nice package.
