### ISSUE TITLE
Important note: response delay

### ISSUE THREAD

**Issue by romgrk** [romgrk/termrk#18]
Hello, 
For the summer, I am working as tree planter in the woods. Therefore, I have no internet connection during the week. Therefore, if you post an issue, I can't respond until the weekend.

Being the only maintainer of this project for the moment, no one can fix anything unless it's the weekend.

While waiting, you can:
- Create a PR and fix it yourself! 
  
  If you have never done it, it's quite easy. Search some doc, and in 20-40 minutes you should be all set to start you first PR.
- Become a maintainer! 
  
  Just send me a message containing a link to some code/repo of yours. If you have none, create a PR extending/creating fixing a feature of Termrk.

**Comment by v3ss0n** [comment]
Ah i c , ok i will help fixing what i can.
