### ISSUE TITLE
  'keystroke': 'native!' dosen't seem to do anything.

### ISSUE THREAD

**Issue by v3ss0n** [romgrk/termrk#20]
I am using byobu inside termrk , and when i tried to open more sessions using `CTRL + A , CTRL + N`, atom creates new empty tabs instead.

So i tried this inside keymap.cson.

```
'.termrk':
  'keystroke': 'native!'
```

But that Dosen't work too.
Bug?

**Comment by zenozeng** [comment]
Hello, 

I just add this to my keymap:

``` coffeescript
'.termrk':
  'ctrl-a': 'native!'
  'ctrl-e': 'native!'
  'ctrl-f': 'native!'
  'ctrl-b': 'native!'
  'ctrl-n': 'native!'
  'ctrl-p': 'native!'
```

All works except ctrl-a, stilling digging why C-a not work.

**Comment by zenozeng** [comment]
seems C-a is used by term.js

**Comment by zenozeng** [comment]
@romgrk Hi, is there anyway to disable the VI feature which captures ctrl-a. I am an emacs guy, and C-a is used to move to the beginning of a line, which is very frequently used.

**Comment by zenozeng** [comment]
Seems turn this line to false will work: https://github.com/romgrk/termrk/blob/ac0f7a55166776ba215b3e984b9deef356eb469a/lib/termrk-view.coffee#L109

@romgrk, what about making this an option?

**Comment by romgrk** [comment]
Agreed. I don't think that screen-keys is an essential feature. I will update tomorrow.

**Comment by romgrk** [comment]
@v3ss0n I guess you figured to replace `'keystroke'` by the actual keystroke that you want to be handled as `'native!'`? 
If there is a problem, let me know.

**Comment by v3ss0n** [comment]
If Ctrl + A works , i'll be fine :)

**Comment by romgrk** [comment]
Done. Closing this, re-open if there is any problem with keystrokes-handling. Thanks.
