### ISSUE TITLE
Enhancement - Selection separate from input?

### ISSUE THREAD

**Issue by ghost** [romgrk/termrk#22]
Hello

Currently, when text is selected in termrk, you can immediately paste it in the terminal itself. This is neat, however you can't continue typing without explicitely clicking in the terminal. It seems that whenever text is selected in termrk, the input cursor can't be used (in other terminals such as GNOME terminal the selection and input cursor are separated). Not sure if this is intentional or perhaps a limitation in Atom?

Thanks in advance

**Comment by romgrk** [comment]
Noted. There are some issues I'll fix first, but I keep this in the TODO list. I'll update next week. (see note https://github.com/romgrk/termrk/issues/18)

**Comment by romgrk** [comment]
I had zero time to check this lately, but I patched this the following way: whenever text is pasted, terminal gains focus. Hence, you can select, paste and continue typing. 
I'm also thinking about leaving it this way. Having multiple elements having «focus» is far from ideal in an environnment like Atom.

**Comment by ghost** [comment]
That's more than satisfactory for my purposes, thanks :).
