### ISSUE TITLE
Termrk do not start at cwd

### ISSUE THREAD

**Issue by v3ss0n** [romgrk/termrk#23]
Choosing CWD  make Termrk starts in  Home directory , not current file's directory.Project or Home setting works.

Does CWD means directory where atom is started or  directory of current file ?

**Comment by romgrk** [comment]
It uses `process.cwd`. Normally, it should always be the same as `project.getPaths()[0]`, I added it just in case it might someday differ. I will change the title and add an option for starting a session in current file's directory.

**Comment by romgrk** [comment]
`startingDir` option has been updated, it now spawns sessions in current file's dir.

**Comment by v3ss0n** [comment]
Thats soo awesome!
