### ISSUE TITLE
High CPU usage after opening terminal

### ISSUE THREAD

**Issue by nodren** [romgrk/termrk#28]
I've noticed very high CPU usage after opening the terminal.  nothing short of restarting atom will fix it.  I'll be happy to provide any details to help diagnose this issue.

I'm on OS X Yosemite if it helps.

Also confirmed that [term2](https://atom.io/packages/term2) package does not suffer this slowdown, which claims to also use pty.js and term.js

**Comment by romgrk** [comment]
Thank you for reporting, it appears that termrk doesn't run well at all on OS X, you're not the first one to suffer this problem.
This is linked to the fact that I do not have a mac, or access to one, and therefore cannot test on OS X.
I will take a deeper look on this issue this week, but I cannot guarantee anything.

**Comment by nodren** [comment]
I'd be happy to submit a PR for you regarding this, any place you suggest I begin looking?

Worth noting that the high CPU usage only starts after calling the terminal for the first time after opening atom, opening more terminals, switching, or hiding them does nothing to squash it or make it worse.

**Comment by ghost** [comment]
@nodren @romgrk Any clue as to what might be causing this?

I wouldn't mind trying to figure this one out :D
