### ISSUE TITLE
Focus terminal on termrk:show

### ISSUE THREAD

**Issue by olmokramer** [romgrk/termrk#30]
It would be nice if the terminal gets focus after calling the `termrk:show` command. Currently it only does this when the terminal is hidden. I would like to use my keybinding for `termrk:show` to focus the terminal when it isn't hidden when the command is called, right now I have to click the terminal when it's already visible.

**Comment by romgrk** [comment]
Accepted, will be included in next patch (releasing before 18:00).

Also added commands `termrk:toggle-focus`, `termrk:focus` and `termrk:blur` for convenience.

**Comment by olmokramer** [comment]
Awesome, thanks!
