### ISSUE TITLE
Exiting the session causes keyboard input to be duplicated.

### ISSUE THREAD

**Issue by ghost** [romgrk/termrk#4]
Hello

Whenever I exit the current shell session using 'exit', all following keyboard input becomes duplicated. Perhaps somehow keyboard handlers are being registered again? Apart from this, this extension is shaping up nicely!

Kind regards

**Comment by romgrk** [comment]
Yep, I know perfectly where this is coming from. 
I'm leaving just now but I should have time to fix that later tonight, thanks!

**Comment by romgrk** [comment]
Should be fine now. 
7ab91dde0590c903ccfdd6df16f45b51cbedb4f3
