### ISSUE TITLE
Atom only pulling v0.1.17

### ISSUE THREAD

**Issue by mjrodgers** [romgrk/termrk#40]
The package installer within Atom only pulls this older version, thought the current should be v0.1.21.

**Comment by romgrk** [comment]
Yes, I noticed it was stuck on v0.1.17 for a while, I thought APM was not updating it ASAP.
I will be looking into this, thanks.

**Comment by romgrk** [comment]
Seems to have resolved by itself at the moment, as I pushed the latest patch; I see v0.1.22 displayed on atom packages. 
Let me know if it still doesn't update.

**Comment by mjrodgers** [comment]
Yes! fixed for me now.

**Comment by romgrk** [comment]
Great! No idea why, but it's fixed!

**Comment by mjrodgers** [comment]
Hmm the newest (now 0.1.27) is again not pulling for me.  Strange.

**Comment by romgrk** [comment]
Yep. I'll try to glance some info on atom forums, to check if anything similar has already happened. I doubt the problem comes from termrk specifically.
