### ISSUE TITLE
Sending selection to terminal does not respect line breaks

### ISSUE THREAD

**Issue by mjrodgers** [romgrk/termrk#44]
I am using termrk to program in an interpreted language (Magma for computer algebra).  However, the line continuation leads to problems with comments.  For example, I can put in a full-line comment using // at the beginning of the line.  But when the line is sent to terminal with a continuation at the end, this makes ALL the following lines a comment.

Example, my code:
// This is a comment
eval_this_code;

But termrk sees:
// This is a comment\
eval_this_code;

And interprets both lines as comments...

**Comment by romgrk** [comment]
Ok, send-selection is having some problems lately, this is next in my TODO list.

**Comment by mjrodgers** [comment]
Thumbs up, thanks for the update!

**Comment by romgrk** [comment]
Fixed by 90b7d8ee2760876ce9293a66baffdc31992c95f5, I have tested it on my side, let me know if it happens again.
