### ISSUE TITLE
terminal limit to 80 chars

### ISSUE THREAD

**Issue by rdcklinux** [romgrk/termrk#46]
When the prompt line has more than 80 chars, this is going to the begining of line, and replace the characters, and hold backspace key, erase all terminal screen.

Atom 1.0.5
Termrk 0.1.22

update today.

**Comment by romgrk** [comment]
Thanks, already fixed. The patch will come out in the next hours.

**Comment by romgrk** [comment]
Fixed by 5d5a78c7b6e89077ca67c3f6ab7b89576d0de1f8.
