### ISSUE TITLE
"send selection to terminal" broken in 0.1.24

### ISSUE THREAD

**Issue by mjrodgers** [romgrk/termrk#51]
I don't get anything in the console or anything.  Just nothing. (OS X 10.10.4)

On the plus side, scrolling works fine now.  Thanks for keeping up the work, by the way, and let me know anything you need me to test on OS X!

**Comment by romgrk** [comment]
Will investigate this tomorrow. Thanks.

**Comment by mjrodgers** [comment]
Still having this issue with the newest version (0.1.26).  I get nothing in the console, but if I open up the keybind resolver, I can see that the command input is registering properly.

**Comment by romgrk** [comment]
Done! Sorry for the delay, everything should be in order now. 90b7d8ee2760876ce9293a66baffdc31992c95f5.

**Comment by ghost** [comment]
This is still an issue. Please see #56
