### ISSUE TITLE
Not working with latest Atom version (Mac OS) "Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom."

### ISSUE THREAD

**Issue by bean5** [romgrk/termrk#64]
/Users/bean5/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/node-gyp-bin/node-gyp: line 3: node: command not found

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/bean5/Downloads/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/bean5/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/bean5/.atom/.apm/.apmrc" "--userconfig" "/Users/bean5/.atom/.apmrc" "rebuild" "--target=0.30.6" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! pty.js@0.2.13 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!

**Comment by romgrk** [comment]
Still happening?

**Comment by ghost** [comment]
This could be the same error I had in #63, if you see a red bug icon in the statusbar at the bottom in the lower right corner, you can click that to open the incompatibility screen where there should be a **Rebuild** button. This solved it for me.

**Comment by bean5** [comment]
@romgrk no longer occurring for me. I am on a new computer and atom has had various updates since I ticketed here--several in one day. I suspect that just as it says in #63 that Atom was temporarily broken.

**Comment by bean5** [comment]
Feel free to close. Thanks for the help @hotoiledgoblinsack.

**Comment by romgrk** [comment]
Great :)
