### ISSUE TITLE
Custom settings are not (entirely?) applied

### ISSUE THREAD

**Issue by ghost** [romgrk/termrk#7]
Hello

It seems custom settings are not applied, after debugging it a little bit it turns out that 'termrk' should be 'Termrk' for them to be applied. For example:

```
// Doesn't work, gives 'undefined'
Config = new Utils.Config('termrk')

// Works
Config = new Utils.Config('Termrk')
```

Strangely enough the defaultHeight option did work without this modification, but the other options would not apply. After this modification everything works as intended here.

**Comment by romgrk** [comment]
Yes, I see very well why this is happening. APM is case-sensitive, but not always, so it probably installed  the package as `Termrk` instead of `termrk` as I have on my computer.
I've published a patch with a test for the package name, let me know how it goes.
