### ISSUE TITLE
does not work at all

### ISSUE THREAD

**Issue by zhang8473** [romgrk/termrk#74]
With key binds fixed in ubuntu 15.10
"create-terminal-current-dir" does not work
'termrk:toggle' works
'ctrl-alt-shift-space' does not work

**Comment by romgrk** [comment]
I would recommend checking if the OS is capturing keystrokes. (`alt-space` specifically)
You can also check if the command is emitted or not with the Atom Keybinding Resolver, normally activated by `ctrl+.`. 
Additionally, you can also rebind any command to a keystroke of your choice in your `keymap.cson`.

Please feel free to reopen if you do notice a bug. In that case it would be good to provided  detailed information. And a decent title.

**Comment by zhang8473** [comment]
I told you. I fixed the key bind conflicts but your ext still sometimes work sometimes does not. I've already deleted your ext and used terminal-plus ext. works ok.
