### ISSUE TITLE
Cycles forward/backward terminal-sessions stop working after close all the sessions

### ISSUE THREAD

**Issue by tinchoz49** [romgrk/termrk#75]
Steps to reproduce:
1. Show the default terminal-session
2. Close the terminal `termrk:close-terminal`
3. Create a new terminal `termrk:create-terminal`
4. Try to use `termrk:activate-next-terminal` and `termrk:activate-previous-terminal`
   Expected Result: Nothing should happen because we only have one terminal-session.
   Current Result: The terminal is closing it when you use the `next` and `previous` commands.

This is the only problem that i found. I try 4 terminals for atom and this is far away the best. Good job!

**Comment by romgrk** [comment]
Noted. Work in progress.

**Comment by romgrk** [comment]
It's all ready but I don't have time to publish, because I have to go to my job. Jobs suck.
See here if you want: https://github.com/romgrk/termrk/tree/experimental
(it includes a better easing function!)

**Comment by tinchoz49** [comment]
thanks for such a quick support @romgrk ! works great with the experimental branch.

**Comment by romgrk** [comment]
Np! Can't seem to remember, but I think I published the patch for this with the last update. (Oh, yes, commit logs say I did. Thanks logs.)
Closing, but dont hesitate to re-open.
