### ISSUE TITLE
After an exit, the width of the console seems incorrect

### ISSUE THREAD

**Issue by ghost** [romgrk/termrk#8]
Hello

It seems that after I enter the exit command and a new shell session is started, the width of the teminal is not correct anymore; whereas at first the amount of columns are calculated based on the entire width of the terminal pane in atom is used, after an exit the width defaults to something like 80 columns, whilst the width of the pane in atom remains the same.

PS: On a related note, if I use bash as shell and have an echo statement of about in my .bashrc file, the output is line wrapped after about 15 characters when the terminal first opens up. The actual prompt has the same problem, but as soon as I start typing, it corrects itself. This problem does not occur when you type the 'exit' command and the session restarts, it only happens the first time the terminal pane opens (perhaps because it is still resizing at that time?).

Thanks in advance

**Comment by romgrk** [comment]
Yep, I am aware of the problem, I haven't found yet how to solve the problem elegantly. I published a semi-patch for this, but I'm not sure it will work on all cases. Let me some more time.

**Comment by ghost** [comment]
Ok, just wanted to let you know that what you have done so far at first sight seems to solve the problem for me :).

EDIT: This was referring to the amount of columns after exit, not to the PS note :P.

**Comment by romgrk** [comment]
I have also semi-patched the PS. Should have been solved with the last upgrade.
