### ISSUE TITLE
Font family and size not immediately applied on startup

### ISSUE THREAD

**Issue by ghost** [romgrk/termrk#9]
Hello

Could be that I messed up some configuration again, but it seems that the font family and size I specified in the settings are not immediately applied. If I open up the settings view and change either of them while termrk is open, they pop into place and correct themselves.

Could it perhaps be that **fontChanged** is not invoked on startup but only on changing settings?

Thanks in advance

**Comment by romgrk** [comment]
Fixed also. Thanks very much for the testing.
