### ISSUE TITLE
bottom-dock package and service (suggestion)

### ISSUE THREAD

**Issue by Gert-dev** [romgrk/termrk#97]
Hello

I've been dropping by in a couple of other Atom packages as well to let developers know about the bottom-dock atom package. You may have already heard about it; it offers a service that allows you to put a customized view in a panel that is docked at the bottom of the atom window.

I realize you already have your own bottom dock implementation, but just wanted to let you know in case you were looking to reduce the code you have to maintain for the dock itself :-). The advantage is that other packages supplying a dock will allow a user to switch between the docks using tabs.

Feel free to close this issue after you've read it and thanks for your package!

**Comment by romgrk** [comment]
Got it, thanks.
